// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function DailyQuote():Promise<internal.ResBody>;

export function GetAppVersion():Promise<string>;
